<a href="https://colab.research.google.com/github/bipinKrishnan/ML_from_scratch/blob/master/linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import torch
from torch.utils.data import DataLoader
from torch import optim
from torch.utils.data import TensorDataset

In [75]:
true_w = torch.tensor([4.2, -3.7]).reshape(2, 1)
true_b = torch.tensor([4.4])

def generate_data(weights, bias):
  features = torch.normal(0, 1, (10, weights.size(0)))
  labels = features@weights+bias

  return features, labels.reshape(-1, 1)

features, labels = generate_data(true_w, true_b)

In [76]:
features.shape, labels.shape

(torch.Size([10, 2]), torch.Size([10, 1]))

In [77]:
dataset = TensorDataset(features, labels)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

##########OR#################
def load_array(data, batch_size, is_train=True):
  data = TensorDataset(*data)
  return DataLoader(data, batch_size, shuffle=is_train)

dataloader1 = load_array((features, labels), 2)

In [78]:
next(iter(dataloader1))

[tensor([[-0.1685, -0.5817],
         [-0.5273,  1.0556]]), tensor([[ 5.8449],
         [-1.7201]])]

In [79]:
net = torch.nn.Sequential(torch.nn.Linear(2, 1))

In [80]:
net[0].weight = torch.nn.Parameter(torch.normal(0, 0.01, (1, 2)))
print(torch.nn.Parameter(torch.normal(0, 0.01, (1, 2))))

###############OR#####################
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)
print("\n", net[0].weight, net[0].bias)

Parameter containing:
tensor([[ 0.0026, -0.0127]], requires_grad=True)

 Parameter containing:
tensor([[0.0023, 0.0116]], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [81]:
next(iter(net.parameters()))

Parameter containing:
tensor([[0.0023, 0.0116]], requires_grad=True)

In [82]:
criterion = torch.nn.MSELoss()
opt = optim.SGD(net.parameters(), lr=0.03)

In [87]:
epochs = 10

for epoch in range(epochs):
  for data, labels in dataloader1:
    opt.zero_grad()
    out = net(data)
    loss = criterion(out, labels)

    loss.backward()
    opt.step()

  print("Epoch: {}/{}  loss: {}".format(epoch+1, epochs, loss.item()))

Epoch: 1/10  loss: 0.05346938967704773
Epoch: 2/10  loss: 0.0019451972329989076
Epoch: 3/10  loss: 0.023427261039614677
Epoch: 4/10  loss: 0.006707999389618635
Epoch: 5/10  loss: 0.02205773815512657
Epoch: 6/10  loss: 1.2233123015903402e-05
Epoch: 7/10  loss: 0.004510745406150818
Epoch: 8/10  loss: 0.003103286027908325
Epoch: 9/10  loss: 5.480849358718842e-05
Epoch: 10/10  loss: 4.442899444256909e-05


In [88]:
net[0].weight, net[0].bias, true_w, true_b

(Parameter containing:
 tensor([[ 4.2010, -3.6817]], requires_grad=True), Parameter containing:
 tensor([4.3887], requires_grad=True), tensor([[ 4.2000],
         [-3.7000]]), tensor([4.4000]))